/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-09-19 08:32:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class myPageMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>마이페이지</title> \r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-color: #ADE8F4;\r\n");
      out.write("        }\r\n");
      out.write("        .wrap {\r\n");
      out.write("            width: 1246px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        #header {\r\n");
      out.write("            width: 1284px;\r\n");
      out.write("            height: 91px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("            box-shadow: 1px 1px 1px 1px rgb(203, 203, 203);\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            max-width: 1300px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 프로필 섹션 */\r\n");
      out.write("        .profile-section {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-section .profile-image {\r\n");
      out.write("            width: 180px;\r\n");
      out.write("            height: 180px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background-color: #E0F7FA;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #6C83A8;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-section .profile-info {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            border: 1px solid #E0E0E0;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-info {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-section .profile-info h6 {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-section .profile-info ul {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-section .profile-info ul li {\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-section .profile-info ul li img {\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-section .profile-buttons {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-section .profile-buttons button {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 축제 섹션 */\r\n");
      out.write("        .interest-section {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            width: 600px;\r\n");
      out.write("            box-shadow: 1px 1px 5px 1px rgb(203, 203, 203);\r\n");
      out.write("        }\r\n");
      out.write("        .interest-section h5 {\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .interest-section .interest-list {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            max-height: 400px;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .interest-section .interest-list li {\r\n");
      out.write("            background-color: #FAFAFA;\r\n");
      out.write("            border: 1px solid #E0E0E0;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .interest-section .interest-list li .info {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .interest-section .interest-list li img {\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .interest-section .interest-list li .text {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        .interest-section .interest-list li .remove {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: red;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 게시글, 댓글 섹션 */\r\n");
      out.write("        .posts-comments-section {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            box-shadow: 1px 1px 5px 1px rgb(203, 203, 203);\r\n");
      out.write("        }\r\n");
      out.write("        .posts-comments-section h5 {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .posts-comments-section ul {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            max-height: 250px;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .posts-comments-section ul li {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            background-color: #FAFAFA;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .posts-comments-section .view-more {\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #6C83A8;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 모달창 */\r\n");
      out.write("        .modal {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background-color: rgba(0,0,0,0.5);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-content {\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            width: 450px;\r\n");
      out.write("            left: 40%;\r\n");
      out.write("            top: 20%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-content > form > table > tr > td {\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .close {\r\n");
      out.write("            float: right;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 모바일 반응형 */\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 480px) {\r\n");
      out.write("            .wrap {\r\n");
      out.write("                padding: 5px;\r\n");
      out.write("            }\r\n");
      out.write("            .profile-section, .interest-section, .posts-comments-section {\r\n");
      out.write("                padding: 5px;\r\n");
      out.write("            }\r\n");
      out.write("            .profile-section .profile-image {\r\n");
      out.write("                width: 100px;\r\n");
      out.write("                height: 100px;\r\n");
      out.write("            }\r\n");
      out.write("            .interest-section .interest-list li .info img {\r\n");
      out.write("                width: 50px;\r\n");
      out.write("                height: 30px;\r\n");
      out.write("            }\r\n");
      out.write("            .posts-comments-section ul li {\r\n");
      out.write("                font-size: 12px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"header\"></div>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!-- Profile Section -->\r\n");
      out.write("            <div class=\"profile-section\">\r\n");
      out.write("                <div class=\"profile-image\" style=\"border: 2px solid #6FBAFF;\">프로필 사진</div>\r\n");
      out.write("                <div class=\"profile-info\" style=\"border: 2px solid #6FBAFF;\">\r\n");
      out.write("                    <h5 style=\"text-align: center;\">내 정보</h5>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><img src=\"./img/profile-icon.png\" alt=\"icon\">아이디: test01</li>\r\n");
      out.write("                        <li><img src=\"./img/profile-icon.png\" alt=\"icon\">이름: 홍길동</li>\r\n");
      out.write("                        <li><img src=\"./img/profile-icon.png\" alt=\"icon\">전화번호: 010-1234-5678</li>\r\n");
      out.write("                        <li><img src=\"./img/profile-icon.png\" alt=\"icon\">주소: 서울특별시</li>\r\n");
      out.write("                        <li><img src=\"./img/profile-icon.png\" alt=\"icon\">주민등록번호: 123456-1234567</li>\r\n");
      out.write("                        <li><img src=\"./img/profile-icon.png\" alt=\"icon\">이메일: test@example.com</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"profile-buttons\">\r\n");
      out.write("                        <button class=\"btn btn-primary\" id=\"edit-profile-btn\">수정하기</button>\r\n");
      out.write("                        <button class=\"btn btn-secondary\" id=\"edit-pwd-btn\">비밀번호 변경</button>\r\n");
      out.write("                        <button class=\"btn btn-danger\" id=\"delete-account-btn\">회원탈퇴</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("            <!-- Interest Section -->\r\n");
      out.write("            <div class=\"interest-section\">\r\n");
      out.write("                <h5>관심등록</h5>\r\n");
      out.write("                <ul class=\"interest-list\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <img src=\"festival.jpg\" alt=\"축제 이미지\">\r\n");
      out.write("                            <div class=\"text\">\r\n");
      out.write("                                <strong>2024 영동 곶감 축제</strong><br>\r\n");
      out.write("                                2024.12.05<br>\r\n");
      out.write("                                1인당 7500원\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"remove\">&times;</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <img src=\"festival.jpg\" alt=\"축제 이미지\">\r\n");
      out.write("                            <div class=\"text\">\r\n");
      out.write("                                <strong>2024 영동 곶감 축제</strong><br>\r\n");
      out.write("                                2024.12.05<br>\r\n");
      out.write("                                1인당 7500원\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"remove\">&times;</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"info\">\r\n");
      out.write("                            <img src=\"festival.jpg\" alt=\"축제 이미지\">\r\n");
      out.write("                            <div class=\"text\">\r\n");
      out.write("                                <strong>2024 영동 곶감 축제</strong><br>\r\n");
      out.write("                                2024.12.05<br>\r\n");
      out.write("                                1인당 7500원\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"remove\">&times;</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <!-- More items -->\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("            <!-- Posts and Comments Section -->\r\n");
      out.write("            <div class=\"posts-comments-section\">\r\n");
      out.write("                <div class=\"posts-comments-container\">\r\n");
      out.write("                    <!-- My Posts Section -->\r\n");
      out.write("                    <div class=\"posts-section\">\r\n");
      out.write("                        <h5>내 게시글</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>게시글 1</li>\r\n");
      out.write("                            <li>게시글 2</li>\r\n");
      out.write("                            <li>게시글 3</li>\r\n");
      out.write("                            <li>게시글 1</li>\r\n");
      out.write("                            <li>게시글 2</li>\r\n");
      out.write("                            <li>게시글 3</li>\r\n");
      out.write("                            <!-- More posts -->\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"view-more\">더 보기</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- My Comments Section -->\r\n");
      out.write("                    <div class=\"comments-section\">\r\n");
      out.write("                        <h5>내 댓글</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>댓글 1</li>\r\n");
      out.write("                            <li>댓글 2</li>\r\n");
      out.write("                            <li>댓글 3</li>\r\n");
      out.write("                            <li>댓글 1</li>\r\n");
      out.write("                            <li>댓글 2</li>\r\n");
      out.write("                            <li>댓글 3</li>\r\n");
      out.write("                            <!-- More comments -->\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"view-more\">더 보기</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 모달 구조 -->\r\n");
      out.write("    <div class=\"modal\" id=\"editProfileModal\" style=\"display:none;\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <span class=\"close\">&times;</span>\r\n");
      out.write("            <h2>프로필 수정</h2>\r\n");
      out.write("            <br>\r\n");
      out.write("            <form>\r\n");
      out.write("                <table>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td style=\"width: 130px;\">\r\n");
      out.write("                            <label for=\"name\">이름:</label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" id=\"name\" name=\"name\" required>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <label for=\"phone\">전화번호:</label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" id=\"phone\" name=\"phone\" required>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <label for=\"address\">주소:</label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" id=\"address\" name=\"address\" required>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <label for=\"ssn\">주민등록번호:</label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" id=\"ssn\" name=\"ssn\" required>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <label for=\"email\">이메일:</label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" id=\"email\" name=\"email\" required> @\r\n");
      out.write("                            <select id=\"email-domain\" name=\"email-domain\">\r\n");
      out.write("                                <option value=\"gmail.com\">@gmail.com</option>\r\n");
      out.write("                                <option value=\"naver.com\">@naver.com</option>\r\n");
      out.write("                                <option value=\"daum.net\">@daum.net</option>\r\n");
      out.write("                                <option value=\"custom\">직접 입력</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <input type=\"text\" id=\"custom-domain\" name=\"custom-domain\" style=\"display:none;\" placeholder=\"직접 입력\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                <br>\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\">저장하기</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        document.getElementById(\"delete-account-btn\").addEventListener(\"click\", function() {\r\n");
      out.write("            if (confirm(\"정말로 회원탈퇴를 진행하시겠습니까?\")) {\r\n");
      out.write("                // 네\r\n");
      out.write("                alert(\"회원탈퇴가 진행됩니다.\");\r\n");
      out.write("            } else {\r\n");
      out.write("                // 아니요\r\n");
      out.write("                alert(\"회원탈퇴가 취소되었습니다.\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 모달 열기 및 닫기 로직\r\n");
      out.write("        var modal = document.getElementById(\"editProfileModal\");\r\n");
      out.write("        var btn = document.getElementById(\"edit-profile-btn\");\r\n");
      out.write("        var span = document.getElementsByClassName(\"close\")[0];\r\n");
      out.write("\r\n");
      out.write("        btn.onclick = function() {\r\n");
      out.write("            modal.style.display = \"block\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        span.onclick = function() {\r\n");
      out.write("            modal.style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        window.onclick = function(event) {\r\n");
      out.write("            if (event.target == modal) {\r\n");
      out.write("                modal.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 이메일 도메인 선택 시 처리\r\n");
      out.write("        var emailDomainSelect = document.getElementById(\"email-domain\");\r\n");
      out.write("        var customDomainInput = document.getElementById(\"custom-domain\");\r\n");
      out.write("\r\n");
      out.write("        emailDomainSelect.onchange = function() {\r\n");
      out.write("            if (emailDomainSelect.value === \"custom\") {\r\n");
      out.write("                customDomainInput.style.display = \"inline-block\";\r\n");
      out.write("            } else {\r\n");
      out.write("                customDomainInput.style.display = \"none\";\r\n");
      out.write("                customDomainInput.value = \"\"; // 입력 필드를 초기화\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
